version: "3"
volumes:
  volume_database_project:

services:
  db:
    image: postgres:16.1
    container_name: aaxis_db
    environment:
      POSTGRES_DB: aaxis
      POSTGRES_USER: aaxis
      POSTGRES_PASSWORD: aaxis
    volumes:
      - ./api/data:/var/lib/mysql
    ports:
      - "5432:5432"

  web:
    build: ./api/.docker
    container_name: project_web
    volumes:
      - ./api:/var/www/html
      - ./api/.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./api/.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "81:80"
    depends_on:
      - db

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "80:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080