version: "3"
volumes:
  volume_database_project:

services:
  db:
    image: postgres:16.1
    container_name: aaxis_db
    environment:
      POSTGRES_DB: aaxis
      POSTGRES_USER: aaxis
      POSTGRES_PASSWORD: aaxis
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "5432:5432"

  web:
    build: ./.docker
    container_name: project_web
    volumes:
      - ./:/var/www/html
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080