nelmio_cors:
    paths:
        '^/token':
            allow_credentials: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/product':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
            max_age: 3600
